perros
apoderados
usuarios roels
roels
usuarios



DROP TABLE USUARIOS_ROLES;
DROP TABLE USUARIOS;
DROP TABLE ROLES;
DROP TABLE PERROS;
DROP TABLE APODERADOS;
DROP TABLE CONSULTAS;
DROP TABLE FACTURAS;
DROP TABLE SUCURSALES;